# .github/workflows/block-no-merge-label.yml
name: Block PRs with "NO-MERGE" label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "NO-MERGE" label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const hasNoMerge = labels.data.some(label => contains(label.name, 'NO-MERGE'));

            if (hasNoMerge) {
              core.setFailed('This pull request has a "NO-MERGE" label.');
            }